name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: check lint
        if: always()
        run: ./gradlew lint

      - name: Build with Gradle
        run: ./gradlew build
      - name: generate AAR and Apk files
        if: always()
        run: ./gradlew assembleDebug
      - name: upload AAR files
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: artifacts.zip
          path:
            app/build/output/apk/debug/app-debug.apk
            app/build/outputs/aar