name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: check lint
        if: always()
        run: ./gradlew lint

      - name: Build with Gradle
        run: ./gradlew build
      #      - name: generate AAR and Apk files
      #        if: always()
      #        run: ./gradlew assembleDebug
      #      - name: upload AAR files
      #        if: always()
      #        uses: actions/upload-artifact@v2
      #        with:
      #          name: artifacts.zip
      #          path:
      #            app/build/output/apk/debug/app-debug.apk
      #            app/build/outputs/aar
      - name: Build release AAB
        id: buildRelease
        run: ./gradlew bundleRelease
      - name: sign AAB
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: create service_account.json
        id: createServiceAccount
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Deploy app to play store (BETA)
        id: deploy
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName: com.demo.demo_circle_ci
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: beta
          whatsNewDirectory: whatsnew/


